### ISSUE TITLE
Subject for Reflections Sent Out on Mail Chimp is Stuck on "The Stuff We Fear"

### ISSUE THREAD

**Issue by abm-webmonk** [abhayagiri/abhayagiri-website#101]
Apologies to burden you with yet another problem happening with the Internet. As of last Friday, June 21, [So and So] has brought to my attention that the Subject line in the Reflections launch has been "stuck" on "Abhayagiri Reflections--The Stuff We Fear."

On further checking, the emailed reflections are launching accordingly; though, they carry that same incorrect subject line: "Abhayagiri Reflections--The Stuff We Fear." That title is from the Friday, June 21 Reflection.

On further investigation, it looks like the Home Page as well as the Reflection Page haven't update the new reflections either and are both "stuck" on the Friday, June 21 reflection.

So, if someone could check to see why this is happening and possibly correct it, would be greatly beneficial and a sure relief to me...

**Comment by abm-devmonk-purple** [comment]
Reportedly resolved.
