### ISSUE TITLE
Filenames for talks are unhuman

### ISSUE THREAD

**Issue by abm-devmonk-purple** [abhayagiri/abhayagiri-website#107]
The filenames for talks are often cryptic/unhuman. For example, for the talk https://www.abhayagiri.org/talks/7197-mind-states-and-metta, the filename is: https://www.abhayagiri.org/media/audio/youtube/jBcaU2ZMXiY.mp3

It would be good if they were more normal names.

**Comment by coderintherye** [comment]
@abm-devmonk-purple It actually downloads as "2019-07-06 Mind States and Metta.mp3" it's just the href link which has the nonhuman name. It does this via applying the "download" attribute https://www.w3schools.com/tags/att_a_download.asp 
Given that, I think you could perhaps consider if you need a change or not?

**Comment by abm-devmonk-purple** [comment]
Probably good enough until somebody reports.
