### ISSUE TITLE
Talk Thumbnail

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#117]
When adding a new talk, we can upload a new image thumbnail, but it doesn't show up on the website.  Thank you!

![image](https://user-images.githubusercontent.com/29779655/64067010-edd2d280-cbd5-11e9-943f-4ed67bb69ee9.png)

**Comment by abm-devmonk-purple** [comment]
It would be good to include images for the rest of the items on the site.
