### ISSUE TITLE
Links on Website Don't Open New Tab

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#118]
Website links in the description section on our Talks page are not opening a new tab when links are clicked.  Thank you!

![image](https://user-images.githubusercontent.com/29779655/64131782-c7509b00-cd7f-11e9-9f12-1b3f7e0bae4a.png)

**Comment by abm-devmonk-purple** [comment]
This should be fixed from commit 169a97517b18e6b483080f00e3b7838b21bfa255
