### ISSUE TITLE
Adding reminder pop-up message for international addresses

### ISSUE THREAD

**Issue by xulin0395** [abhayagiri/abhayagiri-website#120]
After people select their books and are ready to enter their address at: 

https://www.abhayagiri.org/books/request

Under Address -> Country, perhaps we need some type of drop-down menu that reminds people about the international shipping policy if they select other countries. Right now we are getting a few requests each week from people who didn't read the text above and expect us to ship books overseas.

**Comment by abm-devmonk-purple** [comment]
Added in dc6e6b25a0556ef2c21486b2cb99b93904d77e36.
