### ISSUE TITLE
Add buttons to Markdown Macros in WYSIWYG

### ISSUE THREAD

**Issue by abm-devmonk-purple** [abhayagiri/abhayagiri-website#134]
1. We would add a button "Embed" to the WYSIWYG editor. This button would prompt with:

    > Please enter a URL to embed: [_____________]
    > 
    > Examples:
    > 
    > YouTube: https://youtu.be/m02JGV8_WZg
    > Gallery: https://www.abhayagiri.org/gallery/228-winter-retreat-2020
    > Talk: https://www.abhayagiri.org/talks/7339-freedom-from-fear-anxiety

2. The code should parse the input and put in the appropriate embed code, e.g.,

    - YouTube URL/fragment -> `[!embed](https://youtu.be/...)`
    - Gallery URL/path -> `[!embed](/gallery/228)`
    - Talks URL/path -> `[!embed](/talks/7339)`

    If it can't figure out what it is, it should then notify the user with an error.

**Comment by adammparker** [comment]
#154
