### ISSUE TITLE
Filter Dhamma Books by Language and Author 

### ISSUE THREAD

**Issue by abm-webmonk** [abhayagiri/abhayagiri-website#179]
Hello web team, 
I would like to suggest a new feature to the Books portion of the website. The idea is basically to add an initial filter onto the books. It is the ability to filter the selections that are returned by either Author or Language or both. 

The page would remain exactly the same, with the exception that at the beginning would be drop down menus of Authors and Languages. 

This is a (terrible) rendition of how it would look on the first books page. Apologies for the poor photoshop skills, but hopefully you get the idea. I diagrammed the first one on the sidebar for the full webpage. The second one I had the search drop down menus at the top of the list, which would probably be more appropriate for the tablet/phone view. 

![Search Books Sidebar](https://user-images.githubusercontent.com/38106637/86518054-ffcb6600-bde2-11ea-962b-bb81c27ebf82.png)

![Search Books by Languages   Authors](https://user-images.githubusercontent.com/38106637/86517360-26869e00-bddd-11ea-96a3-9d3fbe587a60.png)

On each of the drop down menus it would list each possible Author (there are about 25), and each possible language (I think only 5-6), but the default would be "All Authors," and "All Languages." 

Unfortunately, the books entries on the backend do not have a separate field for "Language." We would need to add a field for "Language" to do this. The only languages of books we have now are English, Thai, Spanish, Chinese, Vietnamese, but there could be more in the future, so it would be good to be able to add languages somehow if possible. 

I imagine that a "Search" button would be necessary to make this work so that people would need to hit search to refresh the entries to reflect only the filtered selections. 

Another, smaller and less important part of this feature is that if the Authors/Languages could be EITHER organized by the number of entries with Authors/Languages with the most books appear at the top of the list and less frequent ones occurring at the bottom of the list OR just listing the number of titles next to the Author/Language on the list (so it would list Spanish (3) as opposed to just Spanish, etc.), that would also be helpful. 

Please let me know if you have any questions. 
Tan Gunaviro

**Comment by belisarh** [comment]
#186
