### ISSUE TITLE
New Talks Not Appearing on Website

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#191]
New Talks aren't showing up at the top of the list in admin or on the website, but when I type the name in the search bar it appears.  However, when I click edit, there is a new section at the bottom that appears blank even after I fill it out.

![image](https://user-images.githubusercontent.com/29779655/97637857-a376fc80-19f8-11eb-96da-a2a9a277e0c0.png)

**Comment by belisarh** [comment]
Solved by #193
