### ISSUE TITLE
Update for Audio Page(s) to make Browsing More available

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#20]
It would be nice to have the Audio Page broken up into several different pages, to make it more friendly to new users who might not know exactly what they are looking for. 

**Breaking up Audio into Several Audio Pages**
My thought right now, which is very flexible, is that we would have several Audio pages broken up by topic and arrangement: e.g.

Seach All Audio 
Dhamma talks by Ajahn
Dhamma talks by Topic
Special Events 
Retreats and Collections
Morning Reflections (I still need to talk about Luang Por about posting these)
Chanting

It might make sense once these are laid out to combine or separate out these pages slightly differently, but I think this would get us most of the way. 

**On the Main Page/Accessing Pages**
To access all of the Audio pages, it would be nice to have a drop down menu to be able to access each of the pages. This would be generally similar to the current drop down menu (labeled "Category"). The only problem is that the current drop down menu is sleek and off to the side, so that I think it's easy to miss and most people don't know to click on it. Also, because the only thing that changes regularly are the Dhamma talks, even if you clicked there once, there's often not a lot of reason to go back, and it might be easy to forget that it is there. What occurs to me to try to deal with that issue is to have that drop down menu happen right after you click on Audio, before you are taken to any of the pages in particular (though I'm totally open to other solutions). 

**On the Layout of each Page**
_Search All Audio_: which would be roughly the same as our currently existing Audio Page. It would have the ability to search and a feed of new Audio Posts with descriptions

_Dhamma talks by Ajahn_: Would be all dhamma talks arranged by Author. 
There would be a first section "Resident Ajahns" which would have each of the Ajahns' names who have lived here for more than a year and given more than a 10 or so talks. Ideally, this would just have a list of Ajahns in this section and then once you click on the Ajahn have it open up into all their talks arranged by year. In this list, there would be just the name of the talk, and to the right of it would have a play button and a download button. If you click on the talk name it would take you to a description of the talk just as the website has currently. 

The second section would be "Visiting Ajahns" which would have each of the visiting Ajahns who have given fewer than 10 talks or 20 talks and who haven't been residents here. 

_Dhamma Talks by Topic_: This would be the most work on my part, but I'm pretty confident that it is an easy project to plug lay people into. The first step on my part would be to have a monk or a guest go through a fairly large number of talks and their descriptions and think about topics that might be of interest to people. As an initial guess on topics that might emerge:
Meditation Instructions
Suffering 
Death and Dying 
Hindrances
Dana
Gratitude
Faith
Renunciation
Sila
Samadhi
Wisdom
Compassion
Metta
Peace and Equanimity
Mindfulness of the Body
Mindfulness of the Breath
The Parts of the Mind
Impermanence and the three characteristics
The Noble Eightfold Path
Nibbana
etc. 

It'll require some work to get started, but eventually, we should be able to tag talks by topic, and then have them automatically sort into the labels. The idea would be to just label a talk with a single label as opposed to having multiple labels for a given talk and have each talk assigned to one topic, but that might be hard. Also, a similar format here, of having the first page have a list of these topics, and then once you click on a given topic, all the talks expand from below, and then be arranged by year. 

Again, I was thinking a similar format for the list of talks of having the name of the talk, the name of the Ajahn, then a play button and a download button. If you clicked on the name of the talk it would take you to another page with the talk description (just as the current website does). 

_Retreats and Special Events_: This would be a similar format of having a list of talks from Thanksgiving and Winter Retreats, Daylongs, as well as Collections, Question and Answer Sessions or Special Events that might not fit neatly into the Dhamma Talks section, and also any other series of talks which might make sense to cluster or download together. 

Similarly I imagine the first section to be Retreats, which would have a list of the names of all the retreats we have audio files for arranged chronologically with the newest ones most recent. Again here on the main page it would ideally just have the name of the retreat, and then if you clicked on a specific retreat you would open up a section listing all of the retreat talks. Similar to before, It would only list the name of the retreat talks, a play button and a download button, but if you clicked on the talk name, it would take you to a description of the talk. 

Also, on this section it would be good to have zip files where someone can download the entire retreat together, but we don't need to do that initially unless it is easy. 

The second section would be Collections, which might include the 20th anniversary compilation, and anything else I can think of that would make sense to cluster together. 

The third section would be Special Events, which I'm thinking would mostly be series of Questions and Answers with visiting Ajahns, series of talks given at the Kathinas or anniversaries, etc. 

All of this would basically be the same as all the previous ones, where on the main page you would just see a list of things like:

Retreats
2017 
  Daylong--Mindfulness of the Body, Ajahn Karunadhammo
2016  
  2016 Thanksgiving Retreat--Mindfulness of the Breath
  Daylong--Ajahn Amaro
  2016 Winter Retreat--Readings from Western Thai Forest Ajahns
2015
  2015 Thanksgiving Retreat--....etc

Collections
2016
 20th Anniversary Compilation of Talks

Special Events
2017
  Luang Por Piak Q&A
2016
  Kathina talks
  Ajahn Dtun Q&A

_Morning Reflections_: Again I still need to talk to Luang Por when he returns about posting these, and I'm still not 100% sure it'll be worth our while to go back and audio edit all the ones of the past, but if I can get a high enough quality where I don't feel like we need to edit the ones of the past, it would be nice to upload them and have them arranged by Month and year. I imagine the general format to be:

2017
   June
   May
   April
  
2016
  December
  November
  October

Then if you clicked on "June" it would open up to all of the morning reflections' names e.g.

2017 
  June
     Gratitude to our Parents, Ajahn Pasanno (Play) (Download) 
     Composing ourselves before going to work, Ajahn Jotipalo (Play) (Download) 
     Getting outside our Lenses of Perception, Ajahn Karunadhammo (Play) (Download) 
  May
  April

2016....

Down the road and going forward it might be nice to label the Morning Reflections by topic as well and assimilate them into that Dhamma Talks by topic Page, but I'll need to do a fair bit of work before that even starts happens. 

_Chanting_
For now this can just be a similar setup for the chanting files for people who want to practice at home. Going forward it would be nice to make it a centralized place for people who want to learn chanting and study the Pali embedded in the chanting at home. We might be able to include some helpful pages on Pali pronunciation. It'll need some work and thinking through, but I thought it made sense to have the chanting separated out. It would also be nice for people to be able to download a zip file of all the most common chanting files. 

For the web layout of the audio I was thinking: 
Chanting
   Daily Chanting
   Paritta Chanting
       Atanatiya Sutta (Play) (Download)
   Other Chanting

Resources for Learning Chanting
   Pali Pronunciation
   Electronic Version of the Chanting Book
   Other Pali Resources

Then when you click on one of them it lists all the audio files for that particular topic. It would be nice to think through adding more resources, but it will also have to be a bit down the line. 

Thanks!

**Comment by abm-avmonk** [comment]
An update to this comment:
For the **Dhamma Talks by Topic**:
I'm thinking the easiest way to organize the massive number of Dhamma talks that we have by Topic is just have each page offer the search results for given terms which are associated with it. 

So, for example, the Genre page on Concentration might be the search results for the words:
"Firm Establishment of the Mind", concentration, focus, calm, tranquility

Also, importantly, we would have to adjust the search to also search through the keywords field as well. I suggested adding this to the list of fields a new Audio Entry could include. I'm already having volunteers tag dhamma talks with as many keywords as seem accurate for that talk.

**Comment by abm-devmonk-purple** [comment]
As of 9cbcdce3ac7d6eff3121c7c4f31e8da987e78cd9, the recent changes to the new talks page seems to have fulfilled this.
