### ISSUE TITLE
Add fields to Audio Entry Page

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#21]
It would be nice to have different fields for Audio Entries between Date Published and Date Given, with the Date Given be the original date the talk was given, and the Date Published be the date it was uploaded to the site.

To be able to sort the new audio entries onto each page and subpage the Audio Entry page will need fields for:
_Type of Audio_: Dhamma Talk, Retreats and Collections, Morning Reflection, Chanting

_Genre_: 
Suffering
Aging and Sickness
Death and Dying
Hindrances
Generosity
Gratitude
Faith
Renunciation
Virtue
Concentration
Wisdom
Compassion
Loving Kindness
Peace and Equanimity
Emptiness
Mindfulness of the Body
Mindfulness of the Breath
The Parts of the Mind
Impermanence 
Not Self
The Noble Eightfold Path
Nibbana

_Keywords_: This would just be a list of keywords which may or may not be included in the description, but which would return the entry through the search function.  

Also, it feels like there needs to be an additional place to tag things with a given Collection, when they are part of a given collection. It seems like it would need to be a drop down menu of the existing collections (e.g. Winter retreat 2017, Spirit Rock Daylong 2017, 20th anniversary compilation, etc.), where the first or last option is "Create a new collection"

_Collection_: (Drop down menu of created collections)

**Comment by abm-devmonk-purple** [comment]
This appears to be done.
