### ISSUE TITLE
Add Talk 500 Internal Server Error

### ISSUE THREAD

**Issue by abm-webmonk** [abhayagiri/abhayagiri-website#210]
Whenever we try to add a talk we get a 500 Internal Server Error. We first noticed this on Sept. 10 but it may have begun earlier. We fill in all the usual form data and then when we click the green "Save and edit this item" at the bottom of the form it presents an orange 500 error page.

**Comment by adammparker** [comment]
Okay, thanks for letting us know. We'll look into this as soon as possible!

**Comment by fsmonter** [comment]
This is fixed.
