### ISSUE TITLE
Allow for Default Picture

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#26]
When adding a new Subject or Teacher or Collection, it would be nice to have the ability to set the default.

The Default Subject picture could be the picture of the Subject Group. 
The Default Teacher picture could be one we have chosen to be the default Teacher picture. 
The Default Collection picture could be one we have chosen to be the default Collections picture.

**Comment by abm-avmonk** [comment]
For adding a new "Author", "Playlist" or "Subject" to the admin section of the website,
https://www.abhayagiri.org/admin/authors
https://www.abhayagiri.org/admin/playlists
https://www.abhayagiri.org/admin/subjects

It would be nice to have the ability to set the default picture associated with each of those. This would probably make sense under Advanced>Settings or Advanced>Default Pictures (which would be another section of Advanced. I expect it would make sense to also be able to set the default Books picture and News picture as well.

**Comment by abm-webmonk** [comment]
I think this is done at least good enough for now. (smiley face)
