### ISSUE TITLE
When Clicking on an Entry in ABMin, Return to Previous Search Results/View

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#27]
After clicking on an entry in ABMin, and pressing "Save and Back" it returns to the original default Talks page or Playlist page. If possible it would be convenient to return to the Search Results or Talks page showing 100 Talks, etc. so as not to have to redo searches and scroll through all the talks or adjust the number of Talks visible every time.

**Comment by abm-devmonk-purple** [comment]
Talks are now 100 by default.
