### ISSUE TITLE
Opening, Uploading, and Registering Media File Takes a Very Long time

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#38]
Opening, uploading, or add the path to a new talk takes often several minutes.

**Comment by abm-webmonk** [comment]
PS - For example, in admin. , when you go to media-> talks -> and then try to upload a talk from the audio folder it takes a long time to open the audio folder. See image below per the location. 

![image](https://user-images.githubusercontent.com/38106637/59371011-b2241d00-8cf8-11e9-8af5-c646a67fff65.png)

**Comment by abm-devmonk-purple** [comment]
Related #96.
