### ISSUE TITLE
Links Don't Seem to Be Working for Several of Thanksgiving Retreats

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#41]
for example:
http://www.abhayagiri.org/new/talks/collections/2-thanksgiving-retreats/1-metta-retreat-2008
"zip file"
"online browsing"
don't link to their respective links

also 
http://www.abhayagiri.org/new/talks/collections/2-thanksgiving-retreats/4-thanksgiving-retreat-2006
"complete set of talks"
doesn't link to it's link.

**Comment by abm-devmonk-purple** [comment]
This was fixed in 3da0ae370cab8294f2e8dcc03da932bfa2de0b80
