### ISSUE TITLE
The pictures of most Ajahns on the talks page are clipped 

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#48]
A little bit on the main teachers page:
https://www.abhayagiri.org/new/talks/teachers
and much more so on each individual teacher's page: e.g.
https://www.abhayagiri.org/new/talks/teachers/12-ajahn-candasiri
the pictures of the teachers are clipped at the top and bottom. 

I believe I was uploading 250x250 pixel pictures.

**Comment by abm-avmonk** [comment]
The same thing seems to be happening on the pictures of the Subjects: e.g.
https://www.abhayagiri.org/new/talks/subjects/2-spiritual-strengths-and-factors-of-awakening/11-faith-and-devotion

**Comment by abm-devmonk-purple** [comment]
It looks like this comes into play at with different resolutions or media queries. We adopted for a convention of uploading photos of these items (teachers/authors, subjects, etc.) at a square aspect ratio of 250x250.

**Comment by luisdalmolin** [comment]
@abm-devmonk-purple I guess we could not force a specific height on the images and let them adjust themselves with the 100% width. A few examples:

![screen shot 2018-01-04 at 17 05 28](https://user-images.githubusercontent.com/403446/34579799-b0876a34-f171-11e7-9933-ff45597e17f2.png)

![screen shot 2018-01-04 at 17 05 57](https://user-images.githubusercontent.com/403446/34579811-b5a63c0c-f171-11e7-8318-b699ea48dd82.png)

What do you think?

**Comment by abm-devmonk-purple** [comment]
@luisdalmolin That looks good to me.
