### ISSUE TITLE
Add Metadata (Title, Collection, Date) to Audio Player Display

### ISSUE THREAD

**Issue by abm-devmonk-purple** [abhayagiri/abhayagiri-website#55]
On the new React front-end, the audio player could use some formatting help. Some particular issues:

- The title of the talk (and other meta data) is absent
- It covers the bottom of the page
- The language switcher doesn't play nicely with it.

On the tablet/desktop:

![image](https://user-images.githubusercontent.com/18488288/34658150-5a5b6512-f3e1-11e7-8b07-4244d69ce521.png)

On mobile:
 
![image](https://user-images.githubusercontent.com/18488288/34658158-6634c2e8-f3e1-11e7-9bfb-7350208be51d.png)

Pagination gets covered:

![image](https://user-images.githubusercontent.com/18488288/34658206-021feb06-f3e2-11e7-9f6f-e87fc08e2a1f.png)

**Comment by abm-avmonk** [comment]
This seems resolved except for the metadata is still not showing up on the webpage.

**Comment by abm-webmonk** [comment]
Seems done good enough for now. (smiley face)
