### ISSUE TITLE
Reorganize Teachers Talks page/Additional Boolean for Author

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#58]
We were thinking of reorganizing the Teachers page to make it more digestible for people. 
http://www.abhayagiri.org/talks/teachers

This would entail three changes. 
First, we would separate out two sections on the talks/teachers page: 1) Residents and Former Residents 2) Visiting Ajahns.  This would require a Boolean to be added to the database Authors variable. 

Secondly, we would like to be able to manually organize the order of each of those sections by "Rank" similarly to the way we can order playlists. 

Thirdly, we were hoping to have a limited number of Teachers available in each of those sections (maybe default to 10?), and then have a more button so that the talks/teachers page would only have about 20 total Teachers/Authors visible. 
![teachers talks page updage](https://user-images.githubusercontent.com/29779655/38457261-c70cc258-3a42-11e8-881d-868bb4dd395c.png)

**Comment by abm-webmonk** [comment]
I think that the current set-up is sufficient. So please do not work on this. Thank you.

**Comment by abm-webmonk** [comment]
Since this issue is 90-95% complete per Adam, let's re-open this issue and finish this off. Thank you.

**Comment by abm-webmonk** [comment]
Done and looks good.
