### ISSUE TITLE
Photo Sort Order 

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#62]
The Sort order for several of the last galleries are set to manual and organized in "Administration" as desired. However, when they show up on the website they come out in a random order. Examples of this are: Concrete Emanates and Bhikkhu Ordination of Gunaviro and Tissaro.

**Comment by abm-devmonk-purple** [comment]
This appears to be fixed in f6354eb75dd45b7393b5257c6cd40c49c22c6306.
