### ISSUE TITLE
Unable to Connect to Backend of the File system ***Important***

### ISSUE THREAD

**Issue by abm-avmonk** [abhayagiri/abhayagiri-website#67]
I was editing a talk and trying to uploading/reuploading talks on the website, and when I pressed the "Browse uploads" Button under "Media File (MP3, etc.)" it gave the error

Unable to connect to backend. HTTP error 418

**Comment by abm-webmonk** [comment]
The system's currently working, but couldn't hurt to look into why this bug would happen in the first place, if that's appropriate, so that it doesn't happen again.
