### ISSUE TITLE
In Abhayagiri Admin, cannot open media/audio folder. 

### ISSUE THREAD

**Issue by abm-webmonk** [abhayagiri/abhayagiri-website#96]
When trying to upload a talk to Media / Audio I received the error message"Unknown Command" after the "Open Folder" process proceeds for a while.

**Comment by abm-devmonk-purple** [comment]
It looks like ecdf9de066c86ad7b0e7653b18fe45a4fd824f98 only partially addressed this issue.

A temporary workaround includes just trying to navigate to the folder again.

**Comment by abm-devmonk-purple** [comment]
The speed also seems more reasonable now.
